targets:
  $default:
    builders:
      injectable_generator|injectable_builder:
        enabled: true
        generate_for:
          include:
            - lib/di/di_objects.dart
            - lib/usecase/**.dart
            - lib/data/**/**.dart
            - lib/presentation/cubit/**.dart

      injectable_generator|injectable_config_builder:
        enabled: true
        generate_for:
          include:
            - lib/di/di.dart

      json_serializable:
        enabled: true
